"""add authentication fields to users

Revision ID: 37a785b58993
Revises: db40663e5e0a
Create Date: 2026-09-07 16:49:03.972649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a785b58993'
down_revision: Union[str, Sequence[str], None] = 'db40663e5e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_id')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
